{
 "title": "mydashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total[$__interval])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "filesystem available bytes %",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"} ) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes ) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "io",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}